Attribute VB_Name = "modMSSGateway"
Option Explicit
Public Const ACK = &H6
Public Const NAK = &H15
Public Const STX = &H2
Public Const ETX = &H3
Public Const ENQ = &H5
Public Const DLE = &H10
Public Const SOH = &H1
Public Const EOT = &H4

Public Const WSAENOERROR = 0                   'No error.
Public Const WSAEINTR = 10004               'System level interrupt interrupted socket operation.
Public Const WSAEBADF = 10009               'Generic error for invalid format, bad format.
Public Const WSAEACCES = 10013              'Generic error for access violation.
Public Const WSAEFAULT = 10014              'Generic error for fault.
Public Const WSAEINVAL = 10022              'Generic error for invalid format, entry, etc.
Public Const WSAEMFILE = 10024              'Generic error for file error.
Public Const WSAEINVIP = 10025              'The IP address provided is not valid or the host specified by the IP does not exist.
Public Const WSAEWOULDBLOCK = 10035         'The specified call would block a non-blocking socket.
Public Const WSAENOTSOCK = 10038            'Invalid socket or not connected to remote.
Public Const WSAEADDRINUSE = 10048          'The specified address is already in use.
Public Const WSAEADDRNOTAVAIL = 10049       'The specified address is not available.
Public Const WSAENETDOWN = 10050            'The connected network is not available.
Public Const WSAENETUNREACH = 10051         'The connected network is not reachable.
Public Const WSAENETRESET = 10052           'The connected network connection has been reset.
Public Const WSAECONNABORTED = 10053        'The current connection has been aborted by the network or intermediate services.
Public Const WSAECONNRESET = 10054          'The current socket connection has been reset.
Public Const WSAENOTCONN = 10057            'The current socket has not been connected.
Public Const WSAESHUTDOWN = 10058           'The connection has been shutdown.
Public Const WSAETIMEDOUT = 10060           'The current connection has timed out.
Public Const WSAECONNREFUSED = 10061        'The requested connection has been refused by the remote host.
Public Const WSAENAMETOOLONG = 10063        'Specified host name is too long.
Public Const WSAEHOSTDOWN = 10064           'Remote host is currently unavailable.
Public Const WSAEHOSTUNREACH = 10065        'Remote host is currently unreachable.
Public Const WSASYSNOTREADY = 10091         'Remote system is not ready.
Public Const WSAVERNOTSUPPORTED = 10092     'Current socket version not supported by application.
Public Const WSANOTINITIALISED = 10093      'Socket API is not initialized.
Public Const WSAEDISCON = 10101             'Socket has been disconnected.
